<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateSessieRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [

            'con1' => 'nullable',
            'con2' => 'nullable',
            'con3' => 'nullable',
            'con4' => 'nullable',
            'con5' => 'nullable',
            'con6' => 'nullable',
            'con7' => 'nullable',
            'con8' => 'nullable',
            'con9' => 'nullable',
            'con10' => 'nullable',
            'con11' => 'nullable',
            'con12' => 'nullable',
            'con13' => 'nullable',
            'con14' => 'nullable',
            'con15' => 'nullable',
            'con16' => 'nullable',
            'con17' => 'nullable',
            'con18' => 'nullable',
            'con19' => 'nullable',
            'con20' => 'nullable',
            'con21' => 'nullable',
            'con22' => 'nullable',
            'con23' => 'nullable',
            'con24' => 'nullable',
            'con25' => 'nullable',
            'con26' => 'nullable',
            'con27' => 'nullable',
            'con28' => 'nullable',
            'con29' => 'nullable',
            'con30' => 'nullable',
            'con31' => 'nullable',
            'con32' => 'nullable',
            'con33' => 'nullable',
            'con34' => 'nullable',
            'con35' => 'nullable',
            'con36' => 'nullable',
            'con37' => 'nullable',
            'con38' => 'nullable',
            'con39' => 'nullable',
            'con40' => 'nullable',
            'con41' => 'nullable',
            'con42' => 'nullable',
            'con43' => 'nullable',
            'con44' => 'nullable',
            'con45' => 'nullable',
            'con46' => 'nullable',
            'con47' => 'nullable',
            'con48' => 'nullable',
            'con49' => 'nullable',
            'con50' => 'nullable',
            'con51' => 'nullable',
            'con52' => 'nullable',
            'con53' => 'nullable',
            'con54' => 'nullable',
            'con55' => 'nullable',
            'con56' => 'nullable',
            'con57' => 'nullable',
            'con58' => 'nullable',
            'con59' => 'nullable',
            'con60' => 'nullable',
            'con61' => 'nullable',
            'con62' => 'nullable',
            'con63' => 'nullable',
            'con64' => 'nullable',
            'con65' => 'nullable',
            'con66' => 'nullable',
            'con67' => 'nullable',
            'con68' => 'nullable',
            'con69' => 'nullable',
            'con70' => 'nullable',
            'con71' => 'nullable',
            'con72' => 'nullable',
            'con73' => 'nullable',
            'con74' => 'nullable',
            'con75' => 'nullable',
            'con76' => 'nullable',
            'con77' => 'nullable',
            'con78' => 'nullable',
            'con79' => 'nullable',
            'con80' => 'nullable',
            'con81' => 'nullable',
            'con82' => 'nullable',
            'con83' => 'nullable',
            'con84' => 'nullable',
            'con85' => 'nullable',
            'con86' => 'nullable',
            'con87' => 'nullable',
            'con88' => 'nullable',
            'con89' => 'nullable',
            'con90' => 'nullable',
            'con91' => 'nullable',
            'con92' => 'nullable',
            'con93' => 'nullable',
            'con94' => 'nullable',
            'con95' => 'nullable',
            'con96' => 'nullable',
            'con97' => 'nullable',
            'con98' => 'nullable',
            'con100' => 'nullable',
            'con101' => 'nullable',
            'con102' => 'nullable',
            'con103' => 'nullable',
            'con104' => 'nullable',
            'con105' => 'nullable',
            'con106' => 'nullable',
            'con107' => 'nullable',
            'con108' => 'nullable',
            'con109' => 'nullable',
            'con110' => 'nullable',
            'con111' => 'nullable',
            'con112' => 'nullable',
            'con113' => 'nullable',
            'con114' => 'nullable',
            'con115' => 'nullable',
            'con116' => 'nullable',
            'con117' => 'nullable',
            'con118' => 'nullable',
            'con119' => 'nullable',
            'con120' => 'nullable',
            'con121' => 'nullable',
            'con122' => 'nullable',
            'con123' => 'nullable',
            'con124' => 'nullable',
            'con125' => 'nullable',
            'con126' => 'nullable',
            'con127' => 'nullable',
            'con128' => 'nullable',
            'con129' => 'nullable',
            'con130' => 'nullable',
            'con131' => 'nullable',
            'con132' => 'nullable',
            'con133' => 'nullable',
            'con134' => 'nullable',
            'con135' => 'nullable',
            'con136' => 'nullable',
            'con137' => 'nullable',
            'con138' => 'nullable',
            'con139' => 'nullable',
            'con140' => 'nullable',
            'con141' => 'nullable',
            'con142' => 'nullable',
            'con143' => 'nullable',
            'con144' => 'nullable',
            'con145' => 'nullable',
            'con146' => 'nullable',
            'con147' => 'nullable',
            'con148' => 'nullable',
            'con149' => 'nullable',
            'con150' => 'nullable',
            'con151' => 'nullable',
            'con152' => 'nullable',
            'con153' => 'nullable',
            'con154' => 'nullable',
            'con155' => 'nullable',
            'con156' => 'nullable',
            'con157' => 'nullable',
            'con158' => 'nullable',
            'con159' => 'nullable',
            'con160' => 'nullable',
            'con161' => 'nullable',
            'con162' => 'nullable',
            'con163' => 'nullable',
            'con164' => 'nullable',
            'con165' => 'nullable',
            'con166' => 'nullable',
            'con167' => 'nullable',
            'con168' => 'nullable',
            'con169' => 'nullable',
            'con170' => 'nullable',
            'con171' => 'nullable',
            'con172' => 'nullable',
            'con173' => 'nullable',
            'con174' => 'nullable',
            'con175' => 'nullable',
            'con176' => 'nullable',
            'con177' => 'nullable',
            'con178' => 'nullable',
            'con179' => 'nullable',
            'con180' => 'nullable',
            'con181' => 'nullable',
            'con182' => 'nullable',
            'con183' => 'nullable',
            'con184' => 'nullable',
            'con185' => 'nullable',
            'con186' => 'nullable',
            'con187' => 'nullable',
            'con188' => 'nullable',
            'con189' => 'nullable',
            'con190' => 'nullable',
            'con191' => 'nullable',
            'con192' => 'nullable',
            'con193' => 'nullable',

            'image' => 'nullable',
            'image2' => 'nullable',
            'image3' => 'nullable',
            'image4' => 'nullable',
            'image5' => 'nullable',
            'image6' => 'nullable',
            'image7' => 'nullable',
            'image8' => 'nullable',

            'image9' => 'nullable',
            'image10' => 'nullable',
            'image11' => 'nullable',
            'image12' => 'nullable',
            'image13' => 'nullable',
            'image14' => 'nullable',
            'image15' => 'nullable',
            'image16' => 'nullable',

        ];
    }
}
