<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateConsultsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('consults', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->integer('dog_id');
            $table->text('con1')->nullable();
            $table->text('con2')->nullable();
            $table->text('con3')->nullable();
            $table->text('con4')->nullable();
            $table->text('con5')->nullable();
            $table->text('con6')->nullable();
            $table->text('con7')->nullable();
            $table->text('con8')->nullable();

            $table->string('con9')->nullable();
            $table->string('con10')->nullable();
            $table->text('con11')->nullable();
            $table->text('con12')->nullable();
            $table->text('con13')->nullable();
            $table->text('con14')->nullable();
            $table->text('con15')->nullable();
            $table->text('con16')->nullable();
            $table->text('con17')->nullable();
            $table->text('con18')->nullable();
            $table->text('con19')->nullable();
            $table->text('con20')->nullable();
            $table->text('con21')->nullable();
            $table->text('con22')->nullable();
            $table->text('con23')->nullable();
            $table->text('con24')->nullable();
            $table->text('con25')->nullable();
            $table->text('con26')->nullable();
            $table->text('con27')->nullable();
            $table->text('con28')->nullable();
            $table->text('con29')->nullable();
            $table->text('con30')->nullable();
            $table->text('con31')->nullable();
            $table->text('con32')->nullable();
            $table->text('con33')->nullable();
            $table->text('con34')->nullable();
            $table->text('con35')->nullable();
            $table->text('con36')->nullable();
            $table->text('con37')->nullable();
            $table->text('con38')->nullable();
            $table->text('con39')->nullable();
            $table->text('con40')->nullable();
            $table->text('con41')->nullable();
            $table->text('con42')->nullable();
            $table->text('con43')->nullable();
            $table->text('con44')->nullable();
            $table->text('con45')->nullable();
            $table->text('con46')->nullable();
            $table->text('con47')->nullable();
            $table->text('con48')->nullable();
            $table->text('con49')->nullable();
            $table->text('con50')->nullable();
            $table->text('con51')->nullable();
            $table->text('con52')->nullable();
            $table->text('con53')->nullable();
            $table->text('con54')->nullable();
            $table->text('con55')->nullable();
            $table->text('con56')->nullable();
            $table->text('con57')->nullable();
            $table->text('con58')->nullable();
            $table->text('con59')->nullable();
            $table->text('con60')->nullable();
            $table->text('con61')->nullable();
            $table->text('con62')->nullable();
            $table->text('con63')->nullable();
            $table->text('con64')->nullable();
            $table->text('con65')->nullable();
            $table->text('con66')->nullable();
            $table->text('con67')->nullable();
            $table->text('con68')->nullable();
            $table->text('con69')->nullable();
            $table->text('con70')->nullable();
            $table->text('con71')->nullable();
            $table->text('con72')->nullable();
            $table->text('con73')->nullable();
            $table->text('con74')->nullable();
            $table->text('con75')->nullable();
            $table->text('con76')->nullable();
            $table->text('con77')->nullable();
            $table->text('con78')->nullable();
            $table->text('con79')->nullable();
            $table->text('con80')->nullable();
            $table->text('con81')->nullable();
            $table->text('con82')->nullable();
            $table->text('con83')->nullable();
            $table->text('con84')->nullable();
            $table->text('con85')->nullable();
            $table->text('con86')->nullable();
            $table->text('con87')->nullable();
            $table->text('con88')->nullable();
            $table->text('con89')->nullable();
            $table->text('con90')->nullable();
            $table->text('con91')->nullable();
            $table->text('con92')->nullable();
            $table->text('con93')->nullable();
            $table->text('con94')->nullable();
            $table->text('con95')->nullable();
            $table->text('con96')->nullable();
            $table->text('con97')->nullable();
            $table->text('con98')->nullable();

            $table->text('con99')->nullable();
            $table->text('con100')->nullable();
            $table->text('con101')->nullable();
            $table->text('con102')->nullable();
            $table->text('con103')->nullable();

            $table->text('con104')->nullable();
            $table->text('con105')->nullable();
            $table->text('con106')->nullable();
            $table->text('con107')->nullable();
            $table->text('con108')->nullable();
            $table->text('con109')->nullable();
            $table->text('con110')->nullable();
            $table->text('con111')->nullable();
            $table->text('con112')->nullable();
            $table->text('con113')->nullable();
            $table->text('con114')->nullable();
            $table->text('con115')->nullable();
            $table->text('con116')->nullable();
            $table->text('con117')->nullable();
            $table->text('con118')->nullable();
            $table->text('con119')->nullable();
            $table->text('con120')->nullable();
            $table->text('con121')->nullable();
            $table->text('con122')->nullable();
            $table->text('con123')->nullable();
            $table->text('con124')->nullable();
            $table->text('con125')->nullable();
            $table->text('con126')->nullable();
            $table->text('con127')->nullable();
            $table->text('con128')->nullable();
            $table->text('con129')->nullable();
            $table->text('con130')->nullable();
            $table->text('con131')->nullable();
            $table->text('con132')->nullable();
            $table->text('con133')->nullable();
            $table->text('con134')->nullable();
            $table->text('con135')->nullable();
            $table->text('con136')->nullable();
            $table->text('con137')->nullable();
            $table->text('con138')->nullable();
            $table->text('con139')->nullable();
            $table->text('con140')->nullable();
            $table->text('con141')->nullable();
            $table->text('con142')->nullable();
            $table->text('con143')->nullable();
            $table->text('con144')->nullable();
            $table->text('con145')->nullable();
            $table->text('con146')->nullable();
            $table->text('con147')->nullable();
            $table->text('con148')->nullable();
            $table->text('con149')->nullable();
            $table->text('con150')->nullable();
            $table->text('con151')->nullable();
            $table->text('con152')->nullable();
            $table->text('con153')->nullable();
            $table->text('con154')->nullable();
            $table->text('con155')->nullable();
            $table->text('con156')->nullable();
            $table->text('con157')->nullable();
            $table->text('con158')->nullable();
            $table->text('con159')->nullable();
            $table->text('con160')->nullable();
            $table->text('con161')->nullable();
            $table->text('con162')->nullable();
            $table->text('con163')->nullable();
            $table->text('con164')->nullable();
            $table->text('con165')->nullable();
            $table->text('con166')->nullable();
            $table->text('con167')->nullable();
            $table->text('con168')->nullable();
            $table->text('con169')->nullable();
            $table->text('con170')->nullable();
            $table->text('con171')->nullable();
            $table->text('con172')->nullable();
            $table->text('con173')->nullable();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('consults');
    }
}
